{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameStorageShares" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.affinity" $ | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "ocis.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "ocis.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["storage-shares", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "ocis.serviceRegistry" . | nindent 12 }}

            - name: STORAGE_SHARES_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: STORAGE_SHARES_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: STORAGE_SHARES_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: STORAGE_SHARES_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: STORAGE_SHARES_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: STORAGE_SHARES_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: STORAGE_SHARES_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: STORAGE_SHARES_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: STORAGE_SHARES_GRPC_ADDR
              value: 0.0.0.0:9154
            - name: STORAGE_SHARES_DEBUG_ADDR
              value: 0.0.0.0:9156

            - name: STORAGE_SHARES_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            {{- include "ocis.caEnv" $ | nindent 12}}

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9154
            - name: metrics-debug
              containerPort: 9156

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            {{- include "ocis.caPath" $ | nindent 12}}

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        {{- include "ocis.caVolume" $ | nindent 8}}
