{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameFrontend" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.serviceAccount" . | nindent 6 }}
      {{- include "ocis.affinity" .Values.services.frontend | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "ocis.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "ocis.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["frontend", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "ocis.serviceRegistry" . | nindent 12 }}

            - name: FRONTEND_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: FRONTEND_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: FRONTEND_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: FRONTEND_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: FRONTEND_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: FRONTEND_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: FRONTEND_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: FRONTEND_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: FRONTEND_HTTP_ADDR
              value: 0.0.0.0:9140
            - name: FRONTEND_DEBUG_ADDR
              value: 0.0.0.0:9141

            - name: FRONTEND_PUBLIC_URL
              value: "https://{{ .Values.externalDomain }}"

            - name: FRONTEND_EVENTS_ENDPOINT
            {{- if not .Values.messagingSystem.external.enabled }}
              value: {{ .appNameNats }}:9233
            {{- else }}
              value: {{ .Values.messagingSystem.external.endpoint | quote }}
            - name: FRONTEND_EVENTS_CLUSTER
              value: {{ .Values.messagingSystem.external.cluster | quote }}
            - name: FRONTEND_EVENTS_ENABLE_TLS
              value: {{ .Values.messagingSystem.external.tls.enabled | quote }}
            - name: FRONTEND_EVENTS_TLS_INSECURE
              value: {{ .Values.messagingSystem.external.tls.insecure | quote }}
            - name: FRONTEND_EVENTS_TLS_ROOT_CA_CERTIFICATE
              {{- if not .Values.messagingSystem.external.tls.certTrusted }}
              value: /etc/ocis/messaging-system-ca/messaging-system-ca.crt
              {{- else }}
              value: "" # no cert needed
              {{- end }}
            {{- end }}

            - name: OCIS_LDAP_SERVER_WRITE_ENABLED
              value: {{ .Values.features.externalUserManagement.ldap.writeable | quote }}

            {{- if .Values.features.externalUserManagement.enabled }}
            - name: FRONTEND_READONLY_USER_ATTRIBUTES
              value: {{ tpl (join "," .Values.features.externalUserManagement.ldap.readOnlyAttributes) . | quote }}
            {{- end }}
            - name: FRONTEND_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            - name: FRONTEND_APP_HANDLER_INSECURE
              value: {{ .Values.insecure.ocisHttpApiInsecure | quote }}

            - name: FRONTEND_ARCHIVER_INSECURE
              value: {{ .Values.insecure.ocisHttpApiInsecure | quote }}

            - name: FRONTEND_OCS_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD
              value: {{ .Values.features.sharing.publiclink.writeableShareMustHavePassword | quote }}

            - name: FRONTEND_SEARCH_MIN_LENGTH
              value: {{ .Values.features.sharing.users.search.minLengthLimit | quote }}

            - name: FRONTEND_ENABLE_RESHARING
              value: {{ .Values.features.sharing.users.resharing | quote }}

            - name: FRONTEND_ARCHIVER_MAX_SIZE
              value: {{ int64 .Values.features.archiver.maxSize | quote }}

            - name: FRONTEND_ARCHIVER_MAX_NUM_FILES
              value: {{ int64 .Values.features.archiver.maxNumFiles | quote }}

            - name: FRONTEND_FULL_TEXT_SEARCH_ENABLED
              value: {{ not (eq .Values.services.search.extractor.type "basic") | quote }}

            # cache
            # the stat cache is disabled for now for performance reasons, see https://github.com/owncloud/ocis-charts/issues/214
            - name: FRONTEND_OCS_STAT_CACHE_STORE
              value: noop

            - name: OCIS_EDITION
              value: {{ .Values.features.edition | quote }}

            - name: FRONTEND_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.machineAuthAPIKeySecret" . }}
                  key: machine-auth-api-key

            - name: FRONTEND_SERVICE_ACCOUNT_ID
              value: .Values.features.serviceAccountID
            - name: FRONTEND_SERVICE_ACCOUNT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.serviceAccountSecret" . }}
                  key: service-account-secret

            - name: OCIS_TRANSFER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.transferSecret" . }}
                  key: transfer-secret

            {{- if .Values.features.quotas.max  }}
            - name: FRONTEND_MAX_QUOTA
              value: {{ .Values.features.quotas.max | quote }}
            {{- end }}

            - name: FRONTEND_AUTO_ACCEPT_SHARES
              value: {{ .Values.features.sharing.autoAcceptShares | quote }}

            {{- include "ocis.cors" . |nindent 12 }}

            # password policies
            - name: FRONTEND_PASSWORD_POLICY_MIN_CHARACTERS
              value: {{ .Values.features.sharing.passwordPolicies.minChars | quote }}
            - name: FRONTEND_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS
              value: {{ .Values.features.sharing.passwordPolicies.minLowerCharacters | quote }}
            - name: FRONTEND_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS
              value: {{ .Values.features.sharing.passwordPolicies.minUpperCharacters | quote }}
            - name: FRONTEND_PASSWORD_POLICY_MIN_DIGITS
              value: {{ .Values.features.sharing.passwordPolicies.minDigits | quote }}
            - name: FRONTEND_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS
              value: {{ .Values.features.sharing.passwordPolicies.minSpecialCharacters | quote }}
            - name: FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST
              value: {{ .Values.features.sharing.passwordPolicies.bannedPasswordsList | quote }}

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: http
              containerPort: 9140
            - name: metrics-debug
              containerPort: 9141

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
