apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: idp
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: idp
        {{- include "ocis.labels" . | nindent 8 }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/idp/secrets.yaml") . | sha256sum }}
    spec:
      containers:
        - name: idp
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["idp", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: IDP_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: IDP_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: IDP_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: IDP_HTTP_ADDR
              value: 0.0.0.0:9130

            - name: IDP_ISS
              value: "https://{{ .Values.externalDomain }}"

            - name: IDP_LDAP_URI
              value: ldaps://idm:9235

            - name: IDP_LDAP_TLS_CACERT
              value: /etc/ocis/ldap-ca/ldap-ca-cert

            - name: IDP_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-bind-secrets
                  key: idp-ldap-bind-password

            - name: IDP_SIGNING_PRIVATE_KEY_FILES
              value: /etc/ocis/idp/private-key.pem

            - name: IDP_ENCRYPTION_SECRET_FILE
              value: /etc/ocis/idp/encryption.key

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9130
          volumeMounts:
            - name: idp-secrets
              mountPath: /etc/ocis/idp
              readOnly: true
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
      volumes:
        - name: idp-secrets
          secret:
            secretName: idp-secrets
        - name: ldap-ca
          secret:
            secretName: ldap-ca
