{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameGraph" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.affinity" $ | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "ocis.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "ocis.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["graph", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "ocis.serviceRegistry" . | nindent 12 }}
            {{- include "ocis.cors" . |nindent 12 }}
            {{- include "ocis.events" . | nindent 12 }}
            {{- include "ocis.cacheStore" . | nindent 12 }}

            - name: GRAPH_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: GRAPH_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: GRAPH_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: GRAPH_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: GRAPH_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: GRAPH_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: GRAPH_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: GRAPH_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: GRAPH_HTTP_ADDR
              value: 0.0.0.0:9120
            - name: GRAPH_DEBUG_ADDR
              value: 0.0.0.0:9124

            - name: GRAPH_SPACES_WEBDAV_BASE
              value: "https://{{ .Values.externalDomain }}"

            - name: GRAPH_IDENTITY_SEARCH_MIN_LENGTH
              value: {{ .Values.features.sharing.users.search.minLengthLimit | quote }}

            {{- if .Values.features.roles.availableUnifiedRoles }}
            - name: GRAPH_AVAILABLE_ROLES
              value: {{ tpl (join "," .Values.features.roles.availableUnifiedRoles) . | quote }}
            {{- end }}

            {{ if not .Values.features.externalUserManagement.enabled }}
            - name: GRAPH_LDAP_URI
              value: ldaps://{{ .appNameIdm }}:9235
            - name: GRAPH_LDAP_CACERT
              value: /etc/ocis/ldap-ca/ldap-ca.crt
            - name: GRAPH_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.ldapBindSecret" . }}
                  key: graph-ldap-bind-password
            {{ else }}
            - name: GRAPH_LDAP_URI
              value: {{ .Values.features.externalUserManagement.ldap.uri | quote }}
            - name: GRAPH_LDAP_BIND_DN
              value: {{ .Values.features.externalUserManagement.ldap.bindDN | quote }}
            - name: GRAPH_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.ldapBindSecret" . }}
                  key: reva-ldap-bind-password
            - name: GRAPH_LDAP_SERVER_WRITE_ENABLED
              value: {{ .Values.features.externalUserManagement.ldap.writeable | quote }}
            - name: GRAPH_LDAP_CACERT
              {{ if or (not .Values.features.externalUserManagement.enabled) (not .Values.features.externalUserManagement.ldap.certTrusted) }}
              value: /etc/ocis/ldap-ca/ldap-ca.crt
              {{ else }}
              value: "" # no cert needed
              {{ end }}
            - name: GRAPH_LDAP_INSECURE
              value: {{ .Values.features.externalUserManagement.ldap.insecure | quote }}
            - name: GRAPH_LDAP_SERVER_UUID
              value: {{ .Values.features.externalUserManagement.ldap.useServerUUID | quote }}
            - name: GRAPH_LDAP_SERVER_USE_PASSWORD_MODIFY_EXOP
              value: {{ .Values.features.externalUserManagement.ldap.passwordModifyExOpEnabled | quote }}

            - name: GRAPH_LDAP_REFINT_ENABLED
              value: {{ .Values.features.externalUserManagement.ldap.refintEnabled | quote }}

            - name: GRAPH_LDAP_USER_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.user.baseDN | quote }}
            - name: GRAPH_LDAP_GROUP_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.group.baseDN | quote }}
            - name: GRAPH_LDAP_GROUP_CREATE_BASE_DN
            {{- if .Values.features.externalUserManagement.ldap.group.createBaseDN }}
              value: {{ .Values.features.externalUserManagement.ldap.group.createBaseDN | quote }}
            {{- else }}
              value: {{ .Values.features.externalUserManagement.ldap.group.baseDN | quote }}
            {{- end }}

            - name: GRAPH_LDAP_USER_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.user.scope | quote }}
            - name: GRAPH_LDAP_GROUP_SEARCH_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.group.scope | quote }}

            - name: GRAPH_USERNAME_MATCH
              value: {{ .Values.features.externalUserManagement.ldap.user.userNameMatch | quote }}

            - name: GRAPH_LDAP_USER_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.user.filter | quote }}
            - name: GRAPH_LDAP_GROUP_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.group.filter | quote }}

            - name: GRAPH_LDAP_USER_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.user.objectClass | quote }}
            - name: GRAPH_LDAP_GROUP_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.group.objectClass | quote }}

            - name: GRAPH_LDAP_USER_UID_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.id | quote }}
            - name: GRAPH_LDAP_GROUP_ID_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.id | quote }}

            - name: GRAPH_LDAP_USER_EMAIL_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.mail | quote }}

            - name: GRAPH_LDAP_USER_DISPLAYNAME_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.displayName | quote }}
            - name: GRAPH_LDAP_USER_NAME_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.userName | quote }}
            - name: GRAPH_LDAP_USER_TYPE_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.userType | quote }}
            - name: GRAPH_LDAP_GROUP_NAME_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.groupName | quote }}

            - name: GRAPH_LDAP_USER_SCHEMA_ID_IS_OCTETSTRING
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.idIsOctetString | quote }}
            - name: GRAPH_LDAP_GROUP_SCHEMA_ID_IS_OCTETSTRING
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.idIsOctetString | quote }}

            - name: GRAPH_USER_ENABLED_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.disableUsers.userEnabledAttribute | quote }}
            - name: GRAPH_DISABLE_USER_MECHANISM
              value: {{ .Values.features.externalUserManagement.ldap.disableUsers.disableMechanism | quote }}
            - name: GRAPH_DISABLED_USERS_GROUP_DN
              value: {{ .Values.features.externalUserManagement.ldap.disableUsers.disabledUsersGroupDN | quote }}

            {{ end }}

            - name: OCIS_SHOW_USER_EMAIL_IN_RESULTS
              value: {{ .Values.features.sharing.users.search.showUserEmail | quote }}

            - name: GRAPH_APPLICATION_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "config.graph" . }}
                  key: application-id

            - name: GRAPH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            - name: OCIS_DEFAULT_LANGUAGE
              value: {{ default "en" .Values.features.language.default | quote }}

            {{- if .Values.features.quotas.default }}
            - name: GRAPH_SPACES_DEFAULT_QUOTA
              value: {{ .Values.features.quotas.default | quote }}
            {{- end }}

            {{- if .Values.features.gdprReport.integrations.keycloak.enabled }}
            - name: GRAPH_KEYCLOAK_BASE_PATH
              value: {{ required "features.gdprReport.integrations.keycloak.basePath needs to be configured when features.gdprReport.integrations.keycloak.enabled is set to true" .Values.features.gdprReport.integrations.keycloak.basePath | quote }}
            - name: GRAPH_KEYCLOAK_CLIENT_ID
              value: {{ required "features.gdprReport.integrations.keycloak.clientID needs to be configured when features.gdprReport.integrations.keycloak.enabled is set to true" .Values.features.gdprReport.integrations.keycloak.clientID | quote }}
            - name: GRAPH_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.gdprExportClientSecret" . }}
                  key: oidc-secret
            - name: GRAPH_KEYCLOAK_CLIENT_REALM
              value: {{ required "features.gdprReport.integrations.keycloak.clientRealm needs to be configured when features.gdprReport.integrations.keycloak.enabled is set to true" .Values.features.gdprReport.integrations.keycloak.clientRealm | quote }}
            - name: GRAPH_KEYCLOAK_USER_REALM
              value: {{ required "features.gdprReport.integrations.keycloak.userRealm needs to be configured when features.gdprReport.integrations.keycloak.enabled is set to true" .Values.features.gdprReport.integrations.keycloak.userRealm | quote }}
            - name: GRAPH_KEYCLOAK_INSECURE_SKIP_VERIFY
              value: {{ .Values.features.gdprReport.integrations.keycloak.insecure | quote }}
            {{- end }}

            - name: GRAPH_SERVICE_ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "config.authService" . }}
                  key: service-account-id
            - name: GRAPH_SERVICE_ACCOUNT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.serviceAccountSecret" . }}
                  key: service-account-secret

            - name: OCIS_ENABLE_OCM
              value: {{ .Values.features.ocm.enabled | quote }}

            {{- include "ocis.caEnv" $ | nindent 12}}

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: http
              containerPort: 9120
            - name: metrics-debug
              containerPort: 9124

          volumeMounts:
            - name: messaging-system-ca
              mountPath: /etc/ocis/messaging-system-ca
              readOnly: true
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
            {{- include "ocis.caPath" $ | nindent 12}}

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: messaging-system-ca
          {{ if and (.Values.messagingSystem.external.enabled) (not .Values.messagingSystem.external.tls.certTrusted) }}
          secret:
            secretName: {{ include "secrets.messagingSystemCASecret" . }}
          {{ else }}
          emptyDir: {}
          {{ end }}
        - name: ldap-ca
          {{ if or (not .Values.features.externalUserManagement.enabled) (not .Values.features.externalUserManagement.ldap.certTrusted) }}
          secret:
            secretName: {{ include "secrets.ldapCASecret" . }}
          {{ else }}
          emptyDir: {}
          {{ end }}
        {{- include "ocis.caVolume" $ | nindent 8}}
