apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: graph
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: graph
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: graph
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["graph", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: GRAPH_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: GRAPH_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: GRAPH_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: GRAPH_DEBUG_PPROF
              value: "{{ .Values.debug.profiling }}"

            - name: GRAPH_HTTP_ADDR
              value: 0.0.0.0:9120
            - name: GRAPH_DEBUG_ADDR
              value: 0.0.0.0:9124

            - name: GRAPH_SPACES_WEBDAV_BASE
              value: "https://{{ .Values.externalDomain }}"

            {{ if not .Values.features.externalUserManagement.enabled }}
            - name: GRAPH_LDAP_URI
              value: ldaps://idm:9235
            - name: GRAPH_LDAP_CACERT
              value: /etc/ocis/ldap-ca/ldap-ca.crt
            - name: GRAPH_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: graph-ldap-bind-password
            {{ else }}
            - name: GRAPH_IDENTITY_BACKEND
              value: cs3
            {{ end }}


            - name: REVA_GATEWAY
              value: gateway:9142
            - name: GRAPH_EVENTS_ENDPOINT
              value: nats:9233

            - name: GRAPH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9120
            - name: metrics-debug
              containerPort: 9124
          {{ if not .Values.features.externalUserManagement.enabled }}
          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
          {{ end }}
      {{ if not .Values.features.externalUserManagement.enabled }}
      volumes:
        - name: ocis-config-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
        - name: ldap-ca
          secret:
            secretName: {{ .Values.secretRefs.ldapCaRef }}
      {{ end }}
