{{- include "ocis.appNames" (dict "scope" . "appName" "appNameStore" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.store.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  replicas: 1 #TODO: https://github.com/owncloud/ocis-charts/issues/113
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.serviceAccount" . | nindent 6 }}
      {{- include "ocis.affinity" .Values.services.store | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- if and $.Values.services.store.persistence.enabled $.Values.services.store.persistence.chownInitContainer }}
      initContainers:
        - name: init-chown-data
          {{- include "ocis.initContainerImage" $ | nindent 10 }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }}", "/var/lib/ocis"]
          volumeMounts:
          - name: store-data
            mountPath: /var/lib/ocis
      {{ end }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["store", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "ocis.serviceRegistry" . | nindent 12 }}

            - name: STORE_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: STORE_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: STORE_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: STORE_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: STORE_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: STORE_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: STORE_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: STORE_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: STORE_GRPC_ADDR
              value: 0.0.0.0:9460
            - name: STORE_DEBUG_ADDR
              value: 0.0.0.0:9464

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9460
            - name: metrics-debug
              containerPort: 9464

          volumeMounts:
            - name: store-data
              mountPath: /var/lib/ocis

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: store-data
          {{ if .Values.services.store.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .appName }}-data
          {{ else }}
          emptyDir: {}
          {{ end }}
