{{- $_ := set . "appName" "store" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: {{ .appName }}
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: grpc
      port: 9460
      protocol: TCP
    - name: metrics-debug
      port: 9464
      protocol: TCP
