{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameUsers" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.affinity" $ | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "ocis.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "ocis.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["users", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "ocis.serviceRegistry" . | nindent 12 }}

            - name: USERS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: USERS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: USERS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: USERS_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: USERS_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: USERS_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: USERS_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: USERS_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: USERS_GRPC_ADDR
              value: 0.0.0.0:9144
            - name: USERS_DEBUG_ADDR
              value: 0.0.0.0:9145

            {{- if .Values.features.externalUserManagement.enabled }}
            - name: USERS_LDAP_INSECURE
              value: {{ .Values.features.externalUserManagement.ldap.insecure | quote }}

            - name: USERS_LDAP_USER_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.user.baseDN | quote }}
            - name: USERS_LDAP_GROUP_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.group.baseDN | quote }}

            - name: USERS_LDAP_USER_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.user.scope | quote }}
            - name: USERS_LDAP_GROUP_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.group.scope | quote }}

            - name: USERS_LDAP_USER_SUBSTRING_FILTER_TYPE
              value: {{ .Values.features.externalUserManagement.ldap.user.substringFilterType | quote }}

            - name: USERS_LDAP_USER_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.user.filter | quote }}
            - name: USERS_LDAP_GROUP_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.group.filter | quote }}

            - name: USERS_LDAP_USER_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.user.objectClass | quote }}
            - name: USERS_LDAP_GROUP_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.group.objectClass | quote }}

            - name: USERS_LDAP_USER_SCHEMA_ID
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.id | quote }}
            - name: USERS_LDAP_GROUP_SCHEMA_ID
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.id | quote }}

            - name: USERS_LDAP_USER_SCHEMA_ID_IS_OCTETSTRING
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.idIsOctetString | quote }}
            - name: USERS_LDAP_GROUP_SCHEMA_ID_IS_OCTETSTRING
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.idIsOctetString | quote }}

            - name: USERS_LDAP_USER_SCHEMA_MAIL
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.mail | quote }}
            - name: USERS_LDAP_GROUP_SCHEMA_MAIL
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.mail | quote }}

            - name: USERS_LDAP_USER_SCHEMA_DISPLAYNAME
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.displayName | quote }}
            - name: USERS_LDAP_GROUP_SCHEMA_DISPLAYNAME
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.displayName | quote }}

            - name: USERS_LDAP_USER_SCHEMA_USERNAME
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.userName | quote }}
            - name: USERS_LDAP_USER_TYPE_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.userType | quote }}
            - name: USERS_LDAP_GROUP_SCHEMA_GROUPNAME
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.groupName | quote }}

            - name: USERS_LDAP_GROUP_SCHEMA_MEMBER
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.member | quote }}

            - name: USERS_LDAP_USER_ENABLED_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.disableUsers.userEnabledAttribute | quote }}
            - name: USERS_LDAP_DISABLE_USER_MECHANISM
              value: {{ .Values.features.externalUserManagement.ldap.disableUsers.disableMechanism | quote }}
            - name: USERS_LDAP_DISABLED_USERS_GROUP_DN
              value: {{ .Values.features.externalUserManagement.ldap.disableUsers.disabledUsersGroupDN | quote }}
            {{- end }}

            - name: USERS_LDAP_URI
            {{ if not .Values.features.externalUserManagement.enabled }}
              value: ldaps://{{ .appNameIdm }}:9235
            {{ else }}
              value: {{ .Values.features.externalUserManagement.ldap.uri | quote }}
            {{ end }}

            - name: USERS_LDAP_CACERT
              {{ if or (not .Values.features.externalUserManagement.enabled) (not .Values.features.externalUserManagement.ldap.certTrusted) }}
              value: /etc/ocis/ldap-ca/ldap-ca.crt
              {{ else }}
              value: "" # no cert needed
              {{ end }}

            {{ if .Values.features.externalUserManagement.enabled }}
            - name: USERS_LDAP_BIND_DN
              value: {{ .Values.features.externalUserManagement.ldap.bindDN | quote }}
            {{ end }}

            - name: USERS_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.ldapBindSecret" . }}
                  key: reva-ldap-bind-password
            - name: USERS_IDP_URL
            {{ if not .Values.features.externalUserManagement.enabled }}
              value: "https://{{ .Values.externalDomain }}"
            {{ else }}
              value: {{ .Values.features.externalUserManagement.oidc.issuerURI | quote }}
            {{ end }}

            - name: USERS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            {{- include "ocis.caEnv" $ | nindent 12}}

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9144
            - name: metrics-debug
              containerPort: 9145

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
            {{- include "ocis.caPath" $ | nindent 12}}

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: ldap-ca
          {{ if or (not .Values.features.externalUserManagement.enabled) (not .Values.features.externalUserManagement.ldap.certTrusted) }}
          secret:
            secretName: {{ include "secrets.ldapCASecret" . }}
          {{ else }}
          emptyDir: {}
          {{ end }}
        {{- include "ocis.caVolume" $ | nindent 8}}
