apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharing
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: sharing
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: sharing
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      containers:
        - name: sharing
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["sharing", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: SHARING_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: SHARING_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: SHARING_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: SHARING_GRPC_ADDR
              value: 0.0.0.0:9150

            - name: REVA_GATEWAY
              value: gateway:9142
            - name: SHARING_EVENTS_ENDPOINT
              value: nats:9233

            - name: SHARING_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            # user sharing
            - name: SHARING_USER_DRIVER
              value: cs3
            - name: SHARING_USER_CS3_PROVIDER_ADDR
              value: storage-system:9215
            - name: SHARING_USER_CS3_SYSTEM_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storageSystemSecretRef }}
                  key: api-key
            - name: SHARING_USER_CS3_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storageSystemSecretRef }}
                  key: user-id

            # public sharing
            - name: SHARING_PUBLIC_DRIVER
              value: cs3
            - name: SHARING_PUBLIC_CS3_PROVIDER_ADDR
              value: storage-system:9215
            - name: SHARING_PUBLIC_CS3_SYSTEM_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storageSystemSecretRef }}
                  key: api-key
            - name: SHARING_PUBLIC_CS3_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storageSystemSecretRef }}
                  key: user-id

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9150
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
