apiVersion: v2
name: ocis
description: ownCloud Infinite Scale (oCIS) Helm chart
keywords:
  - owncloud
  - ocis
maintainers:
  - name: ownCloud GmbH
    email: devops@owncloud.com
    url: https://owncloud.com
type: application
version: 0.5.0
appVersion: 4.0.1
kubeVersion: "" # please see https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#get-the-chart for compatible Kubernetes versions
sources:
  - https://github.com/owncloud/ocis-charts
  - https://github.com/owncloud/ocis
  - https://github.com/cs3org/reva
