apiVersion: v2
name: ocis
description: ownCloud Infinite Scale (oCIS) Helm chart
keywords:
  - owncloud
  - ocis
maintainers:
  - name: ownCloud GmbH
    email: devops@owncloud.com
    url: https://owncloud.com
type: application
version: 0.2.0
appVersion: 3.0.0-rc.2
# supported Kubernetes versions
# should only contain non EOL versions from https://kubernetes.io/releases/patch-releases/#non-active-branch-history
# if this changes, also kubernetesVersions in .drone.star needs to be changed
kubeVersion: "~1.24.0-0 || ~1.25.0-0 || ~1.26.0-0"
sources:
  - https://github.com/owncloud/ocis-charts
  - https://github.com/owncloud/ocis
  - https://github.com/cs3org/reva
