apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: groups
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: groups
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: groups
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["groups", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: GROUPS_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: GROUPS_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: GROUPS_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: GROUPS_GRPC_ADDR
              value: 0.0.0.0:9160

            {{- if .Values.features.externalUserManagement.enabled }}
            - name: GROUPS_LDAP_INSECURE
              value: "{{ .Values.features.externalUserManagement.ldap.insecure }}"

            - name: GROUPS_LDAP_USER_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.user.baseDN }}
            - name: GROUPS_LDAP_GROUP_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.group.baseDN }}

            - name: GROUPS_LDAP_USER_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.user.scope }}
            - name: GROUPS_LDAP_GROUP_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.group.scope }}

            - name: GROUPS_LDAP_USER_SUBSTRING_FILTER_TYPE
              value: {{ .Values.features.externalUserManagement.ldap.user.substringFilterType }}

            - name: GROUPS_LDAP_USER_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.user.filter }}
            - name: GROUPS_LDAP_GROUP_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.group.filter }}

            - name: GROUPS_LDAP_USER_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.user.objectClass }}
            - name: GROUPS_LDAP_GROUP_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.group.objectClass }}

            - name: GROUPS_LDAP_USER_SCHEMA_ID
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.id }}
            - name: GROUPS_LDAP_GROUP_SCHEMA_ID
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.id }}

            - name: GROUPS_LDAP_USER_SCHEMA_ID_IS_OCTETSTRING
              value: "{{ .Values.features.externalUserManagement.ldap.user.schema.idIsOctetString }}"
            - name: GROUPS_LDAP_GROUP_SCHEMA_ID_IS_OCTETSTRING
              value: "{{ .Values.features.externalUserManagement.ldap.group.schema.idIsOctetString }}"

            - name: GROUPS_LDAP_USER_SCHEMA_MAIL
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.mail }}
            - name: GROUPS_LDAP_GROUP_SCHEMA_MAIL
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.mail }}

            - name: GROUPS_LDAP_USER_SCHEMA_DISPLAYNAME
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.displayName }}
            - name: GROUPS_LDAP_GROUP_SCHEMA_DISPLAYNAME
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.displayName }}

            - name: GROUPS_LDAP_USER_SCHEMA_USERNAME
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.userName }}
            - name: GROUPS_LDAP_GROUP_SCHEMA_GROUPNAME
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.groupName }}

            - name: GROUPS_LDAP_GROUP_SCHEMA_MEMBER
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.member }}
            {{- end }}

            - name: GROUPS_LDAP_URI
            {{ if not .Values.features.externalUserManagement.enabled }}
              value: ldaps://idm:9235
            {{ else }}
              value: {{ .Values.features.externalUserManagement.ldap.uri }}
            {{ end }}
            - name: GROUPS_LDAP_CACERT
              {{ if or (not .Values.features.externalUserManagement.enabled) ( not .Values.features.externalUserManagement.ldap.certTrusted) }}
              value: /etc/ocis/ldap-ca/ldap-ca.crt
              {{ else }}
              value: "" # no cert needed
              {{ end }}

            {{ if .Values.features.externalUserManagement.enabled }}
            - name: GROUPS_LDAP_BIND_DN
              value: {{ .Values.features.externalUserManagement.ldap.bindDN }}
            {{ end }}

            - name: GROUPS_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: reva-ldap-bind-password

            - name: GROUPS_IDP_URL
            {{ if not .Values.features.externalUserManagement.enabled }}
              value: https://{{ .Values.externalDomain }}
            {{ else }}
              value: {{ .Values.features.externalUserManagement.oidc.issuerURI }}
            {{ end }}

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: GROUPS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9160
          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            {{ if or (not .Values.features.externalUserManagement.enabled) ( not .Values.features.externalUserManagement.ldap.certTrusted) }}
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
            {{ end }}
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: ocis-config-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
        {{ if or (not .Values.features.externalUserManagement.enabled) ( not .Values.features.externalUserManagement.ldap.certTrusted) }}
        - name: ldap-ca
          secret:
            secretName: {{ .Values.secretRefs.ldapCaRef }}
        {{ end }}
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
