{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameWebdav" "appNameSuffix" "") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: {{ .appName }}
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: http
      port: 9115
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.http | quote}}
    - name: metrics-debug
      port: 9119
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.http | quote}}
