apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
data:
  web.yaml: |
    ---
    web:
      config:
{{- if gt (len .Values.services.web.config.apps) 0 }}
        apps:
{{- toYaml .Values.services.web.config.apps | nindent 10 }}
{{- end }}
{{- if gt (len .Values.services.web.config.externalApplications) 0 }}
        external_apps:
{{- toYaml .Values.services.web.config.externalApplications | nindent 10 }}
{{- end }}
{{- if gt (len .Values.services.web.config.applications) 0 }}
        applications:
{{- toYaml .Values.services.web.config.applications | nindent 10 }}
{{- end }}
        options:
          disableFeedbackLink: {{ .Values.services.web.config.disableFeedbackLink }}
