{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameWeb" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" true) | nindent 4 }}
    spec:
      {{- include "ocis.affinity" $ | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "ocis.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "ocis.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      {{- if or (gt (len $.Values.services.web.additionalInitContainers) 0) (and $.Values.services.web.persistence.enabled $.Values.services.web.persistence.chownInitContainer) }}
      initContainers:
      {{- end }}
      {{- if and $.Values.services.web.persistence.enabled $.Values.services.web.persistence.chownInitContainer }}
        - name: init-chown-data
          {{- include "ocis.initContainerImage" $ | nindent 10 }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          {{- include "ocis.initChownDataCommand" $ | nindent 10 }}
          volumeMounts:
          - name: {{ include "ocis.persistence.dataVolumeName" . }}
            mountPath: /var/lib/ocis
      {{- end }}
      {{- with $.Values.services.web.additionalInitContainers }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["web", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "ocis.serviceRegistry" . | nindent 12 }}
            {{- include "ocis.cors" . |nindent 12 }}

            - name: WEB_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: WEB_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: WEB_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: WEB_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: WEB_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: WEB_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: WEB_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: WEB_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: WEB_HTTP_ADDR
              value: 0.0.0.0:9100
            - name: WEB_DEBUG_ADDR
              value: 0.0.0.0:9104

            - name: WEB_OIDC_AUTHORITY
            {{- if not .Values.features.externalUserManagement.enabled }}
              value: "https://{{ .Values.externalDomain }}"
            {{- else }}
              value: {{ .Values.features.externalUserManagement.oidc.issuerURI | quote }}
            {{- end }}
            - name: WEB_OIDC_CLIENT_ID
              value: {{ .Values.services.web.config.oidc.webClientID | quote }}
            - name: WEB_OIDC_SCOPE
              value: {{ .Values.services.web.config.oidc.webClientScope | quote }}

            - name: WEB_UI_THEME_SERVER
            {{- if .Values.services.web.config.theme.server }}
              value: {{ .Values.services.web.config.theme.server | quote }}
            {{- else }}
              value: https://{{ .Values.externalDomain }}
            {{- end }}
            {{- if .Values.services.web.config.theme.path }}
            - name: WEB_UI_THEME_PATH
              value: {{ .Values.services.web.config.theme.path | quote }}
            {{- end }}

            {{- if .Values.services.web.config.embed.enabled }}
            - name: WEB_OPTION_EMBED_ENABLED
              value: {{ .Values.services.web.config.embed.enabled | quote }}
            {{- end }}

            {{- if .Values.services.web.config.embed.target }}
            - name: WEB_OPTION_EMBED_TARGET
              value: {{ .Values.services.web.config.embed.target | quote }}
            {{- end }}

            {{- if .Values.services.web.config.embed.messagesOrigin }}
            - name: WEB_OPTION_EMBED_MESSAGES_ORIGIN
              value: {{ .Values.services.web.config.embed.messagesOrigin | quote }}
            {{- end }}

            {{- if .Values.services.web.config.embed.delegateAuthentication }}
            - name: WEB_OPTION_EMBED_DELEGATE_AUTHENTICATION
              value: {{ .Values.services.web.config.embed.delegateAuthentication | quote }}
            {{- end }}

            {{- if .Values.services.web.config.embed.delegateAuthenticationOrigin }}
            - name: WEB_OPTION_EMBED_DELEGATE_AUTHENTICATION_ORIGIN
              value: {{ .Values.services.web.config.embed.delegateAuthenticationOrigin | quote }}
            {{- end }}

            {{- if .Values.services.web.config.concurrency.resourceBatchActionRequests }}
            - name: WEB_OPTION_CONCURRENT_REQUESTS_RESOURCE_BATCH_ACTIONS
              value: {{ .Values.services.web.config.concurrency.resourceBatchActionRequests | quote }}
            {{- end }}

            {{- if .Values.services.web.config.concurrency.sseRequests }}
            - name: WEB_OPTION_CONCURRENT_REQUESTS_SSE
              value: {{ .Values.services.web.config.concurrency.sseRequests | quote }}
            {{- end }}

            {{- if .Values.services.web.config.concurrency.shareCreateRequests }}
            - name: WEB_OPTION_CONCURRENT_REQUESTS_SHARES_CREATE
              value: {{ .Values.services.web.config.concurrency.shareCreateRequests | quote }}
            {{- end }}

            {{- if .Values.services.web.config.concurrency.sseRequests }}
            - name: WEB_OPTION_CONCURRENT_REQUESTS_SHARES_LIST
              value: {{ .Values.services.web.config.concurrency.sseRequests | quote }}
            {{- end }}

            - name: WEB_UI_CONFIG_SERVER
              value: "https://{{ .Values.externalDomain }}"

            - name: WEB_OPTION_CONTEXTHELPERS_READ_MORE
              value: {{ .Values.services.web.config.contextHelpersReadMore.enabled | quote }}

            {{- with .Values.features.externalUserManagement.oidc.sessionManagementLink }}
            - name: WEB_OPTION_LOGOUT_URL
              value: {{ . | quote }}
            {{- end }}

            {{- with .Values.features.externalUserManagement.oidc.editAccountLink }}
            - name: WEB_OPTION_ACCOUNT_EDIT_LINK_HREF
              value: {{ . | quote }}
            {{- end }}

            {{- with .Values.services.web.config.oidc.postLogoutRedirectURI }}
            - name: WEB_OIDC_POST_LOGOUT_REDIRECT_URI
              value: {{ . | quote }}
            {{- end }}

            {{- with .Values.services.web.config.oidc.loginURL }}
            - name: WEB_OPTION_LOGIN_URL
              value: {{ . | quote }}
            {{- end }}

            {{- with .Values.services.web.config.userListRequiresFilter }}
            - name: WEB_OPTION_USER_LIST_REQUIRES_FILTER
              value: {{ . | quote }}
            {{- end }}

            - name: WEB_OPTION_DISABLE_FEEDBACK_LINK
              value: {{ not .Values.services.web.config.feedbackLink.enabled | quote }}
            {{- if .Values.services.web.config.feedbackLink.enabled }}
            {{- with .Values.services.web.config.feedbackLink.href }}
            - name: WEB_OPTION_FEEDBACKLINK_HREF
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.services.web.config.feedbackLink.ariaLabel }}
            - name: WEB_OPTION_FEEDBACKLINK_ARIALABEL
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.services.web.config.feedbackLink.description }}
            - name: WEB_OPTION_FEEDBACKLINK_DESCRIPTION
              value: {{ . | quote }}
            {{- end }}
            {{- end }}

            - name: WEB_OPTION_TOKEN_STORAGE_LOCAL
              value: {{ .Values.services.web.config.tokenStorageLocal.enabled | quote }}

            - name: WEB_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            {{- include "ocis.caEnv" $ | nindent 12}}

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: http
              containerPort: 9100
            - name: metrics-debug
              containerPort: 9104

          volumeMounts:
            - name: configs
              mountPath: /etc/ocis
            {{- if .Values.configRefs.webThemeConfigRef }}
            - name: theme
              mountPath: "/var/lib/ocis/web/assets/themes/{{ .Values.services.web.config.theme.themeNameConfigRefs }}"
            {{- end }}
            {{- if .Values.configRefs.webThemeAssetsConfigRef }}
            - name: theme-assets
              mountPath: "/var/lib/ocis/web/assets/themes/{{ .Values.services.web.config.theme.themeNameConfigRefs }}/assets"
            {{- end }}
            - name: apps
              mountPath: /var/lib/ocis/web/assets/apps
            - name: {{ include "ocis.persistence.dataVolumeName" . }}
              mountPath: /var/lib/ocis
            {{- include "ocis.caPath" $ | nindent 12}}

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: configs
          configMap:
            name: {{ .appName }}-config
        {{- with .Values.configRefs.webThemeConfigRef }}
        - name: theme
          configMap:
            name: {{ . | quote }}
        {{- end }}
        {{- with .Values.configRefs.webThemeAssetsConfigRef }}
        - name: theme-assets
          configMap:
            name: {{ . | quote }}
        {{- end }}
        - name: apps
          emptyDir: {}
        {{- include "ocis.caVolume" $ | nindent 8}}
        {{- include "ocis.persistence.dataVolume" . | nindent 8 }}
