{{- if not .Values.features.externalUserManagement.enabled }}
{{- include "ocis.appNames" (dict "scope" . "appName" "appNameIdm" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.idm.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.serviceAccount" . | nindent 6 }}
      {{- include "ocis.affinity" .Values.services.idm | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      initContainers:
      {{- if and $.Values.services.idm.persistence.enabled $.Values.services.idm.persistence.chownInitContainer }}
        - name: init-chown-data
          image: {{ template "ocis.initContainerImage" $ }}
          imagePullPolicy: {{ .Values.initContainerImage.pullPolicy }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }}", "/var/lib/ocis"]
          volumeMounts:
          - name: idm-data
            mountPath: /var/lib/ocis
      {{ end }}
        - name: init-dir #TODO: that should not be needed, needs fix in the idm service
          image: {{ template "ocis.initContainerImage" $ }}
          imagePullPolicy: {{ .Values.initContainerImage.pullPolicy }}
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          command: ["mkdir", "-p", "/var/lib/ocis/idm"]
          resources: {{ toYaml .resources | nindent 12 }}
          volumeMounts:
          - name: idm-data
            mountPath: /var/lib/ocis
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["idm", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: IDM_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: IDM_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: IDM_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: IDM_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: IDM_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: IDM_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: IDM_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: IDM_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: IDM_LDAPS_ADDR
              value: 0.0.0.0:9235
            - name: IDM_DEBUG_ADDR
              value: 0.0.0.0:9239

            - name: IDM_CREATE_DEMO_USERS
              value: {{ .Values.features.demoUsers | quote }}

            - name: IDM_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.adminUserSecretRef }}
                  key: password
            - name: IDM_ADMIN_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.adminUserSecretRef }}
                  key: user-id

            - name: IDM_SVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: graph-ldap-bind-password

            - name: IDM_REVASVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: reva-ldap-bind-password

            - name: IDM_IDPSVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: idp-ldap-bind-password

            - name: IDM_LDAPS_CERT
              value: /etc/ocis/ldap-cert/ldap.crt

            - name: IDM_LDAPS_KEY
              value: /etc/ocis/ldap-cert/ldap.key

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: ldaps
              containerPort: 9235
            - name: metrics-debug
              containerPort: 9239

          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: ldap-cert
              mountPath: /etc/ocis/ldap-cert
              readOnly: true
            - name: idm-data
              mountPath: /var/lib/ocis

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: ocis-config-tmp
          emptyDir: {}
        - name: ldap-cert
          secret:
            secretName: {{ .Values.secretRefs.ldapCertRef }}
        - name: idm-data
          {{ if .Values.services.idm.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .appName }}-data
          {{ else }}
          emptyDir: {}
          {{ end }}
{{- end }}
